### ISSUE TITLE
小程序uni.uploadFile ios兼容报错问题 版本"weapp-cookie": "^1.4.8"

### ISSUE THREAD

**Issue by DudleyLi** [charleslo1/weapp-cookie#69]
MiniProgramError
r.replace is not a function. (In 'r.replace(/\;([^\s\;]*?(?=\=))/gi,",$1")', 'r.replace' is undefined)
TypeError: r.replace is not a function. (In 'r.replace(/\;([^\s\;]*?(?=\=))/gi,",$1")', 'r.replace' is undefined)
at  (appservice.app.js:173:145938)
at  (WAServiceMainContext.js:1:934468)
at <api uploadFile success callback function>
at Vc (WAServiceMainContext.js:1:660474)
at  (WAServiceMainContext.js:1:839991)
at <NetworkUpload10success callback function>
at nv (WAServiceMainContext.js:1:772138)
at forEach (native code)
at emit (WAServiceMainContext.js:1:772779)
at c (WAServiceMainContext.js:1:841457)
at BS (WAServiceMainContext.js:1:842804)
at  (WAServiceMainContext.js:1:843420)
at  (WAServiceMainContext.js:1:634748)
at  (WAServiceMainContext.js:1:625380)
at emit (WAServiceMainContext.js:1:119586)
at emit (native code)
at emit (WAServiceMainContext.js:1:119205)
at subscribeHandler (WAServiceMainContext.js:1:125589)

**Comment by DudleyLi** [comment]
找到报错的源头了
![image](https://github.com/user-attachments/assets/e833a950-8b36-48fd-9658-88e226e79326)

**Comment by shidao-ap5** [comment]
你这么解决的
